### ISSUE TITLE
Mcmmo not working on my 1.12 server

### ISSUE THREAD

**Issue by malbosia2013** [mcMMO-Dev/mcMMO-Classic#3] opened 2019-01-06 19:58 UTC
here is a link to my logs:  https://mclo.gs/zdr0RTE

i do not know how to fix the issue, please help.

**Comment by nossr50** [comment] 2019-01-06 20:01
This bug is caused by invalid values (or keys) that were left over from previous versions of mcMMO
Right now mcMMO does not fix this for you, a quick solution is to delete the .yml files
I'll be implementing a fix for this in the future

https://github.com/mcMMO-Dev/mcMMO-Classic/issues/2#issuecomment-451764004

**Comment by t00thpick1** [comment] 2019-01-06 20:30
@malbosia2013 1.6 is not compatible with 1.12 unfortunately.  the Spigot/Bukkit API has been making a lot of incompatible changes in these major updates, and we have to choose to support one or the other.

**Closed by t00thpick1** 2019-01-06 20:30 UTC

**Comment by nossr50** [comment] 2019-01-06 20:40
whoops didn't notice he was running 1.12 👍

**Comment by malbosia2013** [comment] 2019-01-07 02:41
what version will work with 1.12?
